import React from "react";
import Check from "../Components/Check/Check";
import Header from "../Components/Base/Header/Header";
import Footer from "../Components/Base/Footer/Footer";
import Head from "next/head";
import Statusbar from "../Components/atoms/Statusbar/Statusbar";
import Headline from "../Components/atoms/Headline/Headline";

const Confirm = () => {
  const statusContent: string[] = [
    "アンケート入力",
    "回答確認",
    "アンケート送信",
  ];
  return (
    <div>
      <Head>
        <title>お客様アンケート | 確認</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Headline subject="お客様アンケート" />
        <Statusbar status={statusContent} location={1} />
        <Check />
      </main>
      <Footer />
    </div>
  );
};

export default Confirm;
