import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SubmitHandler, useForm } from "react-hook-form";

type Inputs = {
  sex: string;
  age: number;
  satisfaction: number;
  books: string | undefined;
};

export default function Home() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = (data) => {
    alert(JSON.stringify(data));
  };

  return (
    <>
      <Head>
        <title>websys-2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mt-5">
        <h2 className={styles.title}>
          <span>アンケート</span>
        </h2>
        <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
          <label htmlFor="" className={`mt-3 ${styles.label}`}>
            Q1:性別
          </label>
          <div>
            <label htmlFor="male">
              <input
                required
                className={styles.radio}
                type="radio"
                value="male"
                {...register("sex", { required: true })}
                id="male"
              />
              男性
            </label>
          </div>
          <div>
            <label htmlFor="female">
              <input
                required
                className={styles.radio}
                type="radio"
                value="female"
                {...register("sex", { required: true })}
                id="female"
              />
              女性
            </label>
          </div>
          <div>
            <label htmlFor="undefinded">
              <input
                required
                className={styles.radio}
                type="radio"
                value="none"
                {...register("sex", { required: true })}
                id="undefinded"
              />
              未回答
            </label>
          </div>
          <label htmlFor="" className={`mt-3 ${styles.label}`}>
            Q2:年齢
          </label>
          <div>
            <select id="" {...register("age", { required: true })}>
              <option value="10">10歳〜</option>
              <option value="20">20歳〜</option>
              <option value="30">30歳〜</option>
              <option value="40">40歳〜</option>
              <option value="50">50歳〜</option>
              <option value="60">60歳〜</option>
              <option value="70">70歳〜</option>
              <option value="80">80歳〜</option>
              <option value="90">90歳〜</option>
              <option value="100">100歳〜</option>
            </select>
          </div>
          <label htmlFor="" className={`mt-3 ${styles.label}`}>
            Q3:Y書店の満足度
          </label>
          <div className="mt-1">
            <label htmlFor="satisfaction-5">
              <input
                {...register("satisfaction", { required: true })}
                required
                className={styles.radio}
                type="radio"
                name="satisfaction"
                value="5"
                id="satisfaction-5"
                checked
              />
              とても満足
            </label>
          </div>
          <div>
            <label htmlFor="satisfaction-4">
              <input
                {...register("satisfaction", { required: true })}
                className={styles.radio}
                type="radio"
                name="satisfaction"
                value="4"
                id="satisfaction-4"
              />
              満足
            </label>
          </div>
          <div>
            <label htmlFor="satisfaction-3">
              <input
                {...register("satisfaction", { required: true })}
                className={styles.radio}
                type="radio"
                name="satisfaction"
                value="3"
                id="satisfaction-3"
              />
              どちらでもない
            </label>
          </div>
          <div>
            <label htmlFor="satisfaction-2">
              <input
                {...register("satisfaction", { required: true })}
                className={styles.radio}
                type="radio"
                name="satisfaction"
                value="2"
                id="satisfaction-2"
              />
              不満
            </label>
          </div>
          <div>
            <label htmlFor="satisfaction-1">
              <input
                {...register("satisfaction", { required: true })}
                className={styles.radio}
                type="radio"
                name="satisfaction"
                value="1"
                id="satisfaction-1"
              />
              とても不満
            </label>
          </div>
          <label htmlFor="" className={`mt-3 ${styles.label}`}>
            Q4:最近買ってよかった本
          </label>
          <div>
            <input
              {...register("books")}
              type="text"
              className={`${styles.text} p-3`}
            />
          </div>
          <input className="btn btn-primary mt-3" type="submit" value="送信" />
        </form>
      </main>
    </>
  );
}
