import Head from "next/head";
import React, { useEffect } from "react";
import Header from "../Components/Base/Header/Header";
import Statusbar from "../Components/atoms/Statusbar/Statusbar";
import Headline from "../Components/atoms/Headline/Headline";
import Footer from "../Components/Base/Footer/Footer";
import TextArea from "../Components/atoms/TextArea/TextArea";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { RootState } from "../store";

const Thanks = () => {
  const statusContent: string[] = [
    "アンケート入力",
    "回答確認",
    "アンケート送信",
  ];

  useEffect(() => {
    window.location.reload();
  }, []);

  return (
    <>
      <Head>
        <title>お客様アンケート</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Headline subject="お客様アンケート" />
        <Statusbar status={statusContent} location={2} />
        <div style={{ margin: "100px auto", textAlign: "center" }}>
          <TextArea text="アンケートの送信が完了しました" />
          <TextArea text="ご協力ありがとうございました" />
        </div>
      </main>
      <Footer />
    </>
  );
  return <></>;
};

export default Thanks;
